moveit_sim_hw_interface:
  joint_model_group: arm_group, hand_group
  joint_model_group_pose: init_pose, open
controller_list:
  - name: fake_arm_group_controller
    joints:
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
      - joint6output_to_joint6
  - name: fake_hand_group_controller
    joints:
      - finger_joint1
      - finger_joint2
      
initial:
  - group: arm_group
    pose: init_pose
  - group: hand_group
    pose: open
